[tool.poetry]
name = "dumpyara"
version = "1.0.2"
description = "Android firmware extractor"
authors = ["Sebastiano Barezzi <barezzisebastiano@gmail.com>"]
license = "GPL-3.0"
readme = "README.md"
repository = "https://github.com/sebaubuntu-python/dumpyara"

[tool.poetry.scripts]
dumpyara = 'dumpyara.main:main'

[tool.poetry.dependencies]
python = "^3.8"
Brotli = "^1.0.9"
protobuf = "^4.22.1"
sebaubuntu-libs = "^1.3.2"
liblp = "^1.0.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
